FROM maven:3.9.4-eclipse-temurin-17

# Встановлення Allure CLI
RUN apt-get update && apt-get install -y unzip curl && \
    curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip && \
    unzip allure.zip -d /opt/ && \
    ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure

WORKDIR /project