version: '3.8'

services:
  tests:
    image: maven:3.9-eclipse-temurin-17
    container_name: autotest-tests
    volumes:
      - .:/usr/src/app
      - allure-results:/usr/src/app/allure-results
    working_dir: /usr/src/app
    command: mvn clean test
    environment:
      - DISPLAY=:99
      - JAVA_OPTS=-Djava.awt.headless=true

  allure:
    image: frankescobar/allure-docker-service
    container_name: autotest-allure
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results
      - allure-reports:/app/allure-reports
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1

volumes:
  allure-results:
  allure-reports: