version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.21.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - network

  chrome1:
    image: selenium/node-chrome:4.21.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - network

  chrome2:
    image: selenium/node-chrome:4.21.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - network

  selenide-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenide-tests
    environment:
      - RUN_ENV=docker
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
    volumes:
      - ./src:/app/src
      - ./target/allure-results:/app/target/allure-results
#      - ./target/allure-report:/app/target/allure-report
#      - ./run-tests.sh:/app/run-tests.sh
    working_dir: /app
#    user: "${UID}:${GID}"
    depends_on:
      - selenium-hub
    networks:
      - network

  allure-service:
    image: frankescobar/allure-docker-service:2.13.8
    container_name: allure-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
      PUID: 1000
      PGID: 1000
    ports:
      - "5050:5050"
    volumes:
      - ./target/allure-results:/app/allure-results
      - ./target/allure-report:/app/default-reports
    networks:
      - network

networks:
  network:
    driver: bridge