FROM maven:3.9.4-eclipse-temurin-17

WORKDIR /project
COPY . /project

# Запуск тесту

RUN mvn install
RUN mvn clean test -Dtest=web.simple.ExampleTest2

# Показати вміст allure-results
RUN echo "🧪 Allure results:" && ls -la /project/allure-results