version: '3.8'

services:
  selenide-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    user: root
    environment:
      - RUN_ENV=docker
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
    volumes:
      - ./src:/app/src
      - ./crm/target/allure-results:/app/target/allure-results
    working_dir: /app
    depends_on:
      - selenium-hub
    networks:
      - shared_network

networks:
  shared_network:
    external: true