version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /data/crm:/var/jenkins_home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - TZ=Europe/Kyiv
    networks:
      - shared_network

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d:ro
      - /data/nginx/html:/usr/share/nginx/html:ro
      - /data/nginx/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - shared_network

  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: hub
    user: root
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: unless-stopped
    networks:
      - shared_network

  chrome1:
    image: selenium/node-chrome:4.21.0
    container_name: chrome1
    user: root
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: unless-stopped
    networks:
      - shared_network

  chrome2:
    image: selenium/node-chrome:4.21.0
    container_name: chrome2
    user: root
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true