services:

  chrome1:
    image: selenium/standalone-chrome:latest
    shm_size: 12gb
    ports:
      - "4441:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=60

  tests1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chrome1
    environment:
      - BROWSER=chrome
      - SELENIUM_REMOTE_URL=http://chrome1:4444/wd/hub
      - RUN_ENV=remote
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
#    command: mvn test -DsuiteXmlFile=src/test/java/resources/testng.xml && ls -la /app/allure-results
    command: mvn test -DsuiteXmlFile=src/test/java/resources/testngRun1.xml && ls -la /app/allure-results

  allure:
    image: frankescobar/allure-docker-service:latest
    ports:
      - "172.24.48.1:5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    command: sh -c "allure generate /app/allure-results --clean -o /app/allure-report && tail -f /dev/null"
volumes:
  jenkins_home:

