version: '3.8'

services:
  selenide-tests:
    build: .
    container_name: selenide-chrome-tests
    volumes:
      - ./src:/app/src
      - ./test-results:/app/test-results
      - ./logs:/app/logs
    environment:
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - SELENIDE_BROWSER=chrome
      - SELENIDE_HEADLESS=true
      - SELENIDE_BROWSER_SIZE=1920x1080
    working_dir: /app
    command: >
      sh -c "
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 2 &&
        ./gradlew test --info
      "
    networks:
      - selenide-network

networks:
  selenide-network:
    driver: bridge