version: '3.8'

services:
  selenide-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test1
    environment:
      - SELENIDE_BROWSER=chrome
      - SELENIDE_HEADLESS=true
      - SELENIDE_BROWSER_SIZE=1920x1080
      - DISPLAY=:99
    working_dir: /app
    shm_size: 2gb
    networks:
      - selenide-network

networks:
  selenide-network:
    driver: bridge